resolver: lts-22.39

packages:
- '.'

# Uncomment to test with hinotify before 0.3.10, when the API switched to use RawFilePath
# extra-deps:
# - hinotify-0.3.9
# allow-newer: true

extra-deps:
- vty-windows-0.2.0.3
